package view;

//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

import model.Equation;

public class GUI_HOME extends JPanel {
  private JLabel lblTitle;
  private JLabel lblSubTitle;
  private JButton btnBegin;
  private JButton btnAbout;
  private JButton btnBackground;
  private JLabel lblEquation;
  private JTextField txtLeftEquation;
  private JLabel lblEqualSign1;
  private JTextField txtRightEquation;
  private JLabel lblResult;
  private JTextField txtResultLeft;
  private JLabel lblEqualSign2;
  private JTextField txtResultRight;
  private JTextArea txtAreaInstructions;
  private JButton btnGo;
  private JButton btnInstructions;
  
  private Equation eq;
  
  public GUI_HOME() {
      //construct components
      lblTitle = new JLabel ("CHEMICAL EQUATION BALANCER");
      lblSubTitle = new JLabel ("USING MATRIX EQUATIONS");
      btnBegin = new JButton ("Begin");
      btnAbout = new JButton ("About");
      btnBackground = new JButton ("Background");
      lblEquation = new JLabel ("Balance Equation:");
      txtLeftEquation = new JTextField (1);
      lblEqualSign1 = new JLabel ("=");
      txtRightEquation = new JTextField (1);
      lblResult = new JLabel ("Result:");
      txtResultLeft = new JTextField (1);
      lblEqualSign2 = new JLabel ("=");
      txtResultRight = new JTextField (1);
      txtAreaInstructions = new JTextArea (5, 1);
      btnGo = new JButton ("GO!");
      btnInstructions = new JButton ("Instructions");

      //set components properties
      txtAreaInstructions.setEnabled (false);

      //adjust size and set layout
      setPreferredSize (new Dimension (768, 476));
      setLayout (null);

      //add components
      add (lblTitle);
      add (lblSubTitle);
      add (btnBegin);
      add (btnAbout);
      add (btnBackground);
      add (lblEquation);
      add (txtLeftEquation);
      add (lblEqualSign1);
      add (txtRightEquation);
      add (lblResult);
      add (txtResultLeft);
      add (lblEqualSign2);
      add (txtResultRight);
      add (txtAreaInstructions);
      add (btnGo);
      add (btnInstructions);

      //set component bounds (only needed by Absolute Positioning)
      lblTitle.setBounds (290, 30, 195, 45);
      lblSubTitle.setBounds (305, 55, 160, 25);
      btnBegin.setBounds (40, 115, 115, 25);
      btnAbout.setBounds (40, 435, 115, 25);
      btnBackground.setBounds (40, 400, 115, 25);
      lblEquation.setBounds (225, 115, 115, 25);
      txtLeftEquation.setBounds (340, 115, 145, 25);
      lblEqualSign1.setBounds (490, 115, 20, 20);
      txtRightEquation.setBounds (505, 115, 145, 25);
      lblResult.setBounds (225, 150, 100, 25);
      txtResultLeft.setBounds (340, 150, 145, 25);
      lblEqualSign2.setBounds (490, 150, 20, 25);
      txtResultRight.setBounds (505, 150, 145, 25);
      txtAreaInstructions.setBounds (40, 190, 460, 185);
      btnGo.setBounds (550, 190, 100, 25);
      btnInstructions.setBounds (40, 150, 115, 25);
      
      hideInstructions();
      hideBalance();
  }
  private void hideBalance(){
	  lblEquation.setVisible(false);
      lblResult.setVisible(false);
      txtLeftEquation.setVisible(false);
      txtRightEquation.setVisible(false);
      txtResultLeft.setVisible(false);
      txtResultRight.setVisible(false);
      lblEqualSign1.setVisible(false);
      lblEqualSign2.setVisible(false);
      
      btnGo.setVisible(false);
  }
  private void showBalance(){
	  lblEquation.setVisible(true);
      lblResult.setVisible(true);
      txtLeftEquation.setVisible(true);
      txtRightEquation.setVisible(true);
      txtResultLeft.setVisible(true);
      txtResultRight.setVisible(true);
      lblEqualSign1.setVisible(true);
      lblEqualSign2.setVisible(true);
      
      btnGo.setVisible(true);
  }
  
  private void showInstructions(){
	  txtAreaInstructions.setVisible(true);
	  setInstructions();
  }
  
  private void hideInstructions(){
	  txtAreaInstructions.setVisible(false);
  }
  
  private void showAboutDialog(){

	  JOptionPane.showMessageDialog(null,"CREATORS: \nDY, AAKOV \nMENDOZA, MA.THERESA \nUNABIA,KARL"
	  		+ "\n\nDecember 6, 2015");
  }
  
  private void setInstructions(){
	  txtAreaInstructions.setDisabledTextColor(Color.BLACK);
	  txtAreaInstructions.setText("\n  Instructions:\n\n"
	  		+ "  No Spaces.\n\n"
	  		+ "  Enter the Equations in this format:\n"
	  		+ "\t\tMgO+Fe = Fe2O3+Mg\n\n"
	  		+ "  Equations that will lead to square diagonals are unbalanceable.");
  }
  
  public void showListeners(){
	  btnBegin.addActionListener(new BalanceActionListener());
	  btnInstructions.addActionListener(new BalanceActionListener());
	  btnAbout.addActionListener(new BalanceActionListener());
	  btnGo.addActionListener(new BalanceActionListener());
  }
  
  private void clearTextBoxes(){
	  txtLeftEquation.setText("");
	  txtRightEquation.setText("");
	  txtResultLeft.setText("");
	  txtResultRight.setText("");
  }
  
  class BalanceActionListener implements ActionListener{

	public void actionPerformed(ActionEvent e) {
		if(e.getSource().equals(btnBegin)){
			clearTextBoxes();
			showBalance();
			hideInstructions();
		}
		else if(e.getSource().equals(btnInstructions)){
			hideBalance();
			showInstructions();
		}
		else if(e.getSource().equals(btnAbout)){
			showAboutDialog();
		}
		else if(e.getSource().equals(btnGo)){
			
			String left = new String(txtLeftEquation.getText());
			String right = new String(txtRightEquation.getText());
			
			eq = new Equation(left, right);
			
			String newLeft = new String(eq.getLeftEquation());
			String newRight = new String(eq.getRightEquation());
			
			System.out.println(newLeft);
			System.out.println(newRight);
			
			txtResultLeft.setText(newLeft);
			txtResultRight.setText(newRight);
			
		}
		
	}
	  
  }
  public static void main (String[] args) {
	  GUI_HOME gui = new GUI_HOME();
      JFrame frame = new JFrame ("ADVDISC - Chemical Equation Balancer");
      frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
      frame.getContentPane().add (gui);
      frame.pack();
      frame.setLocation(250,150);
      frame.setVisible (true);
      
      gui.showListeners();

  }
}
